services:
  disportal:
    container_name: disportal
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
      args:
        - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
        - SECRET=${SECRET}
        - VITE_SITE_NAME=${VITE_SITE_NAME}
        - VITE_SITE_URL=${VITE_SITE_URL}
    restart: always
    depends_on:
      - disportal-db
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.disportal.rule=Host(`disportal.coding.global`) || Host(`www.disportal.coding.global`)"
      - "traefik.http.routers.disportal.entrypoints=websecure"
      - "traefik.http.routers.disportal.tls.certresolver=letsencrypt"
      - "traefik.http.services.disportal.loadbalancer.server.port=3000"
  disportal-db:
    container_name: disportal-db
    image: postgres:latest
    restart: always
    networks:
      - proxy
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  proxy:
    external: false
    name: proxy
