name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          touch .env

          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} > .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env

          echo SECRET=${{ secrets.SECRET }} >> .env
          echo VITE_SITE_NAME=${{ secrets.VITE_SITE_NAME }} >> .env
          echo VITE_SITE_URL=${{ secrets.VITE_SITE_URL }} >> .env

      # - name: Reset DB
      #   run: docker stop disboard-scrape-db || true && docker rm disboard-scrape-db || true

      - name: Docker run
        run: docker compose up -d --force-recreate --build

      - name: remove unused images, containers, volumes, and networks
        run: docker image prune -a -f --filter "until=24h" && docker container prune -f --filter "until=24h" && docker volume prune -f && docker network prune -f --filter "until=24h"
